import 'bootstrap-icons/font/bootstrap-icons.css';

import 'bootstrap/dist/css/bootstrap.css';

import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import "./variables.css";
import Header from "@/components/Header";

const inter = EB_Garamond ({ subsets: ['latin']})

export const metadata: Metadata = {
  title: "Music Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
